spring:
  application:
    name: platform-assistant-api
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      chat:
        options:
          model: gpt-4o-mini
    mcp:
      client:
        enabled: true
        name: platform-assistant-api-mcp-client
        stdio:
          connections:
            github:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - GITHUB_PERSONAL_ACCESS_TOKEN
                - ghcr.io/github/github-mcp-server
              env:
                GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PAT}

