spring:
  application:
    name: platform-assistant-api
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
    mcp:
      client:
        enabled: true
        name: platform-assistant-api-mcp-client
        stdio:
          connections:
            github:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - GITHUB_PERSONAL_ACCESS_TOKEN
                - ghcr.io/github/github-mcp-server
              env:
                GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PAT}
            aws-eks:
              command: docker
              args:
                - run
                - -i
                - --rm
                - -e
                - AWS_ACCESS_KEY_ID
                - -e
                - AWS_SECRET_ACCESS_KEY
                - -e
                - AWS_REGION
                - awslabs/eks-mcp-server
                - --allow-sensitive-data-access
              env:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
                AWS_REGION: us-east-1

