spring:
  application:
    name: platform-assistant-api
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key-here}
      chat:
        options:
          model: gpt-4o-mini
    mcp:
      client:
        enabled: true
        servers:
          github:
            type: http
            url: https://api.githubcopilot.com/mcp/
            headers:
              Authorization: Bearer ${GITHUB_PERSONAL_ACCESS_TOKEN:your-github-token-here}

